### ISSUE TITLE
cobra.io.read_sbml_model model loading errors

### ISSUE THREAD

**Issue by math248** [opencobra/schema#13]
Hi everybody,
I'am new in the CBM using Cobrapy. So I tried to read an SBML model of chlorella available in open source, however when I run this commande on a python script I have plenty of errors that I don't understand. 
CODE 
import numpy as np
import cobra
import os
from os.path import join
Auto_Model = cobra.io.read_sbml_model(join("iCZ843_Model_Heterotrophy.xml"))

ERRORS 
WARNING:cobra.io.sbml:Model does not contain SBML fbc package information.
Academic license - for non-commercial use only
WARNING:cobra.io.sbml:SBML package 'layout' not supported by cobrapy,information is not parsed
WARNING:cobra.io.sbml:SBML package 'render' not supported by cobrapy,information is not parsed
WARNING:cobra.io.sbml:Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_c "10-Formyltetrahydrofolate">
WARNING:cobra.io.sbml:Use of FORMULA in the notes element is discouraged, use fbc:chemicalFormula instead: <Species M_10fthf_h "10-Formyltetrahydrofolate">

Thank you in advance guys.

**Comment by Midnighter** [comment]
Hi @math248,

Unfortunately, this is not the right repository. Please open issues on https://github.com/opencobra/cobrapy/issues/new in future.

However, from what you have posted I only see warnings and no actual errors. What is not working for you?

**Comment by math248** [comment]
Hi Moritz,
Sorry if I came in the wrong group with this particular problem. The think
is that with this simple code I have a lot of errors. I only want to see
the summary FBA that they processed on this microorganism. And I don't
understand because I was able to see it before I updated pip.
CODE :

```
import numpy as np
import cobra
import os
from os.path import join
import logging
# it allows the view of all the warniings and error from the python code
and log it in a file
logging.basicConfig(filename='test.log',level=logging.DEBUG)
Hetero_Model =
cobra.io.read_sbml_model(join("PP2016-00593DR3_Data1Model_Heterotrophy.xml"))
solution = Hetero_Model.summary()
print(solution)
```

ERRORS when I compile the code:

```
Academic license - for non-commercial use only
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    solution = Hetero_Model.summary()
  File
"/home/mathieu/.local/lib/python2.7/site-packages/cobra/core/model.py",
line 1202, in summary
    fva=fva, names=names, floatfmt=floatfmt)
  File
"/home/mathieu/.local/lib/python2.7/site-packages/cobra/flux_analysis/summary.py",
line 192, in model_summary
    lambda x: format_long_string(x.name.id, 15), 1)
  File
"/home/mathieu/.local/lib/python2.7/site-packages/pandas/core/frame.py",
line 3370, in __setitem__
    self._set_item(key, value)
  File
"/home/mathieu/.local/lib/python2.7/site-packages/pandas/core/frame.py",
line 3444, in _set_item
    self._ensure_valid_index(value)
  File
"/home/mathieu/.local/lib/python2.7/site-packages/pandas/core/frame.py",
line 3426, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that
cannot be converted to a Series
```

Thanks Again and sorry for the trouble,
Regards.

**Comment by Midnighter** [comment]
If you follow the steps detailed in the documentation at https://cobrapy.readthedocs.io/en/latest/simulating.html#Simulating-with-FBA do you also get errors? Because that works for me and I don't have access to your model.

**Comment by math248** [comment]
When I tried with the cobra.test proposed for training it did worked and
the first time I tried with the iCZ843model in
autotrophy/Mixotrophy/Heterotrophy it worked too. However after the pip
update and even after the reinstallation of my OS, it failed.
If I try this code to have the model BOF :

solution = model.optimize()
print(solution)

It returns "<Solution 0.000 at 0x7f355a660b90>" when before I had the
optimzed solution of the model.


Le mer. 3 avr. 2019 à 16:50, Moritz E. Beber <notifications@github.com> a
écrit :

**Comment by Midnighter** [comment]
So I've downloaded one of the models from http://www.plantphysiol.org/content/suppl/2016/07/02/pp.16.00593.DC1 I hope that's what you were talking about.

In the recent update we switched the cobrapy SBML parser to use the official libsbml package. It looks like the published model has a lot of problems. One of the things that may have changed since updating the parser is that now the model doesn't have a defined objective.

You can inspect that by looking at `model.objective.expression`.

So I installed cobra version 0.14.2 and loaded the model. The defined objective there is `Biomass_Cvu_hetero_DASH_`. Then I ran it with the latest cobra version again (0.15.1) and set that objective:

```python
model.objective = model.reactions.Biomass_Cvu_hetero_DASH_
```

and then the summary works again.

**Comment by Midnighter** [comment]
@matthiaskoenig do you have any immediate idea why the objective is no longer parsed?

**Comment by math248** [comment]
It works when I set the objective function after loading the model. In the future, if the model has no objective function properly set, how can I set it ? Do I have to go trough the file or is there any python function that can locate it in the SBML file ? 
Thanks again guys :-)

**Comment by Midnighter** [comment]
From the Python side you can try to look for a reaction that contains the string `'growth'` or `'biomass'` with the query method (see code below). Otherwise I would search through the SBML file with an editor.

```python
model.reactions.query('[Bb]iomass', attribute='name')
model.reactions.query('[Gg]rowth', attribute='name')
```

**Comment by matthiaskoenig** [comment]
@Midnighter and @math248 Sorry for the late reply, just came back from holidays. I will have a look at the SBML related issues this week. Which supplemental file did you download?
I am very sure there is a very unconventional way to define the objective used in the SBML and will implement a fallback solution for that.

**Comment by Midnighter** [comment]
I chose the [heterotrophy mode](http://www.plantphysiol.org/highwire/filestream/12153/field_highwire_adjunct_files/0/PP2016-00593DR3_Data1Model_Heterotrophy.xml) for my test. Probably the others will show the same behavior.

> I am very sure there is a very unconventional way to define the objective used in the SBML and will implement a fallback solution for that.

Agreed. It would be good to know why (or rather based on which criterion) the previous parser managed to set the objective compared to the current one.

**Comment by matthiaskoenig** [comment]
@Midnighter Can you close the issue. 
Tracking this via https://github.com/opencobra/cobrapy/issues/834
